default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    upload_to_play_store(
      track: 'production',
      release_status: 'completed',
      apk: ENV.fetch('APK_PATH', 'fugitive-release.apk'),
      skip_upload_metadata: false,
      skip_upload_images:   false,
      skip_upload_screenshots: false
    )
  end

  desc "Upload to internal testing track"
  lane :internal do
    upload_to_play_store(
      track: 'internal',
      apk: ENV.fetch('APK_PATH', 'fugitive-release.apk')
    )
  end
end
