name: Publish Release → itch.io

on:
  release:
    types: [published]

jobs:
  upload_to_itch:
    # skip prereleases – remove the line below if you want them as well
    if: ${{ github.event.release.prerelease == false }}
    runs-on: ubuntu-latest

    steps:
      - name: Download release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dist
          gh release download ${{ github.event.release.tag_name }} \
            -R ${{ github.repository }} \
            -D dist

      - name: Set up Butler
        uses: jdno/setup-butler@v1

      - name: Push every build to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
        run: |
          butler push dist/fugitive-windows-release.zip  stumpy-dog-studios/fugitive:windows-release --userversion ${{ github.event.release.tag_name }}
          butler push dist/fugitive-linux-release.zip    stumpy-dog-studios/fugitive:linux-release   --userversion ${{ github.event.release.tag_name }}
          butler push dist/fugitive-osx-release.zip      stumpy-dog-studios/fugitive:osx-release     --userversion ${{ github.event.release.tag_name }}
          butler push dist/fugitive.apk  stumpy-dog-studios/fugitive:android-release --userversion ${{ github.event.release.tag_name }}